{% set name = "aiohappyeyeballs" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohappyeyeballs-{{ version }}.tar.gz
  sha256: 7e1ae8399c320a8adec76f6c919ed5ceae6edd4c3672f4d9eae2b27e37c80ff6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0

test:
  imports:
    - aiohappyeyeballs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohappyeyeballs
  summary: Happy Eyeballs for asyncio
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
