{% set name = "aiohappyeyeballs" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fdd7d87889c63183afc18ce9271f9b0a7d32c2303e394468dd45d514a757745

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python

test:
  imports:
    - aiohappyeyeballs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aio-libs/aiohappyeyeballs
  dev_url: https://github.com/aio-libs/aiohappyeyeballs
  doc_url: https://aiohappyeyeballs.readthedocs.io/
  summary: Happy Eyeballs for asyncio
  description: |
    This library exists to allow connecting with Happy Eyeballs (RFC 8305)
    when you already have a list of addrinfo and not a DNS name.
  license: PSF-2.0
  license_family: Other
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
