{% set name = "aiohappyeyeballs" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3f9d0113123803ccadfdf3f0faa505bc78e6a72d1cc4806cbd719826e943558

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - poetry-core >=2.0.0
    - pip
  run:
    - python

test:
  source_files:
    - tests/
  imports:
    - aiohappyeyeballs
  requires:
    - pip
    - pytest >=7
    - pytest-asyncio >=0.23.2
  commands:
    - pip check
    - pytest tests/ -v

about:
  home: https://github.com/aio-libs/aiohappyeyeballs
  dev_url: https://github.com/aio-libs/aiohappyeyeballs
  doc_url: https://aiohappyeyeballs.readthedocs.io/
  summary: Happy Eyeballs for asyncio
  description: |
    This library exists to allow connecting with Happy Eyeballs (RFC 8305)
    when you already have a list of addrinfo and not a DNS name.
  license: PSF-2.0
  license_family: Other
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
